name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21

      # 关键修改：使用 shadowJar 任务而非 build
      - name: Build with Gradle
        run: ./gradlew shadowJar --full-stacktrace

      # 添加调试步骤，列出所有 JAR 文件
      - name: List generated JAR files
        run: find . -name "*.jar"
      # 上传完整工作目录（包含所有生成文件）
      - name: Upload Entire Workspace
        uses: actions/upload-artifact@v4
        with:
          name: full-environment
          path: ${{ github.workspace }}
          retention-days: 7  # 自动保留天数（可选）

      # 上传 Shadow JAR（主构建产物）
      - name: Upload HuskSync Shadow JAR
        uses: actions/upload-artifact@v4
        with:
          name: HuskSync
          path: build/libs/HuskSync-*.jar
          retention-days: 7
