name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace
        
      - name: list folders
        run: ls ./bukkit
        
      - uses: actions/upload-artifact@v2
        with:
          name: HuskSync-Bukkit
          path: bukkit/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: HuskSync-Common
          path: common/build/libs
      - uses: actions/upload-artifact@v2
        with:
          name: HuskSync
          path: plugin/build/libs
